### ISSUE TITLE
GridFS adapater

### ISSUE THREAD

**Issue by rodrigok** [jalik/jalik-ufs#1]
Are you planing to create an adapter to save files in MongoDB?

We are planing to migrate from CollectionFS to this package but we need to save files in DB by default to make installations more easy.

Maybe I can help you to create this package, I did somethings with GridFS https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-file/file.server.coffee

**Comment by jalik** [comment]
Hi @rodrigok, I would appreciate for sure any help from good devs (I like clean work ;-).
Thank you for your help, we can work on it together, here is the repository containing the ufs-gridfs package ready to work on : https://github.com/jalik/jalik-ufs-gridfs

**Comment by rodrigok** [comment]
Nice @jalik, I'll work on it ASAP :smiley:

**Comment by rodrigok** [comment]
Hey @jalik, do you have a test project?

**Comment by jalik** [comment]
Hi @rodrigok, I've just created a simple one, you can use it to work :)
https://github.com/jalik/ufs-example

**Comment by rodrigok** [comment]
Thanks @jalik

**Comment by rodrigok** [comment]
@jalik I need more information of file in method **getWriteStream**.

I saw that you has this information here https://github.com/jalik/jalik-ufs/blob/master/ufs-uploader.js#L55 but you don't use it.

Can you change it to pass this information to method **ufsComplete** and then to method **store.getWriteStream**?

I did my first work with GridFS adapter, you can see here https://github.com/rodrigok/jalik-ufs-gridfs

**Comment by jalik** [comment]
@rodrigok, the **file** object is passed to the Uploader to be inserted before actually uploading, you missed it but I use the **file** object here : https://github.com/jalik/jalik-ufs/blob/master/ufs-uploader.js#L177

Since the inserted file does not change from the beginning of the upload until the end, I don't see why it should be passed to **ufsComplete** method, BUT if what you want is getting file info like content-type, I can pass the file object that I get directly from database before calling `store.getWriteStream` with the file object as second argument :
```js
ufsComplete: function(fileId, storeName) {
    // ...
    var file = this.getCollection().findOne(fileId);
    // This is what you need
    store.getWriteStream(fileId, file);
    //...
}
```
I did read your code on **ufs-gridfs**, nice work, clean and concise ! ;-)

**Comment by rodrigok** [comment]
:smile_cat: 

Thanks @jalik, when you will upload to atmosphere?

**Comment by jalik** [comment]
@rodrigok, I will commit when the problem with transformRead will be solved, so very soon.

**Comment by rodrigok** [comment]
If you need help with **transformRead** you can describe it more and I will try to help you :)

**Comment by jalik** [comment]
Implemented in **ufs-gridfs** store : https://github.com/jalik/jalik-ufs-gridfs
