### ISSUE TITLE
Transform files before save the temporary

### ISSUE THREAD

**Issue by rodrigok** [jalik/jalik-ufs#125]
Hi @jalik 

What do you think about add an option to transform files while saving the temp file?

I'm developing an adapter to S3 and it requires the file size before init the (almost fake) stream, and if I add a transformation on the middle I can't figure out the final file size to make the upload works.

My current solution for that is add the transformation before seve the temp file to disk then when we start the stream to S3 we already know the final file size cuz there is no need for a new transformation.

I can develop it quickly if you accept the idea, and I can try to publish a updated adapter to S3 soon.

Thanks

**Comment by jalik** [comment]
Hi @rodrigok, I am always glad to see improvements and suggestions from the community.
But I don't really understand if that involves code modifications in the UploadFS "core" package.
Could you show a very basic algo, or at least detail how you want to proceed ? (step 1, 2, 3...).
Thank you.

**Comment by rodrigok** [comment]
Sorry @jalik, forgot about that, I was trying to implement it and just realized that the uploads is made via chunks (multiple POSTs) so there is no way to intercept the stream cuz there are multiple streams :(

I'll try to solve my problem transforming the file in a sync way inside the method `onValidate`. 

I'll let you know if I have success on that 😄

**Comment by jalik** [comment]
In fact you should have everything you need (metadata, size, etc) when the temp file is complete and right before uploading to the store, also pre and post transformation are already handled by UploadFS so I don't really understand your goal, sorry I've probably missed something.

FYI, you could write your own client uploader and use it instead of the official one.
You could also write your own server upload code to upload differently than with chunks (I am almost sure you can, haven't checked it but pretty sure it is possible).

Just to know, streams are not available on browsers right ? because when I created this package I made some searches and ended not using streams because they weren't available, I started uploading using meteor methods (websocket) but performances were very poor for large files, this is why I switched to classic HTTP POST.
