### ISSUE TITLE
Where are files stored?

### ISSUE THREAD

**Issue by emenoh** [jalik/jalik-ufs#15]
I've configured a local fs store and when I upload it is displaying the image, however when I restart the meteor app the image becomes broken. Also I can not find where in my filesystem the image is being store - if at all. Seems like it's cached in memory or something. 

Can you provide some insight on where files should be stored within the meteor app structure? [app]/public/[path]... or [app]/[path] or ???

Thanks!

p.s. I'm using the grid-fs module now which is working fine. Still interested to know why the local fs module isn't working as expected.

**Comment by jalik** [comment]
Hi @emenoh, the local-store package is working as intended, you just haven't configured it yet, so it uses default path which is the meteor app root path, and because (I guess) you're in a development meteor environment, each time you change a file and meteor rebuild the app, every file is deleted included uploaded files... if you were in production environment it would not behave like that.

The documentation for UploadFS-Local tells you to define a path where to store files on local filesystem : https://github.com/jalik/jalik-ufs-local#create-a-store

It is not explained in the doc that the default path is the app root dir because you don't need to know as in most cases you erase this value by setting your own upload path.

Note : you should never store uploaded files within the app tree, but in an external folder (eg : /uploads), this is the default behavior but only for test purposes. Your app will be upgraded one day so you don't want to loose files by putting them in a sub-folder.
