### ISSUE TITLE
How to create thumbnails?

### ISSUE THREAD

**Issue by miri-am** [jalik/jalik-ufs#17]
I understand that you can use transformWrite to resize an image. But how would you proceed when you want to save the image in original quality and in addition as a thumbnail? Do I have to use a different store for that and use `upload.start();`twice?

**Comment by jalik** [comment]
Hi @miri-am, it's true that currently there is no examples of how to create thumbnails, it's because currently there is no "official" way to do it. For now you could do like this :

**Temporary solution**

You save the original file without transforming it, then you define a **transformRead(from, to, fileId, file, request)** in your store to return a resized version of the image depending on what arguments are passed in the URL, I think you can get them with **request.queryParams** (ex: http://example.com/ufs/images/a2DkfS.jpg?thumb=200x200). This would however resize the original image on each request so you could improve this mechanism by saving the generated thumbnail in a cache to return it later.

**Future solution**

In fact, I've started coding the **UploadFS.store.Multi** that could be used to upload files to several stores on the fly (ex: Amazon S3 + local filesystem + mongo GridFS in a single upload).
You could also use it to save different version of the file (like thumbnails), a single default store would then be used to return the file. That will be the official way to do that because it's easier, cleaner and more flexible, but it still not ready. The main advantage is that if you delete a file from a multi store, it would delete from all the stores it handles so you would not have to do that yourself !

This is how you would declare a thumbnail Muli store :
```js
// Images collection
Meteor.images = new Mongo.Collection('images');

// Images local store
Meteor.originalLocalStore = new UploadFS.store.Local({
    collection: Meteor.images,
    name: 'original',
    path: '/uploads/images'
});

// Thumbnails collection
Meteor.thumbs = new Mongo.Collection("thumbnails");

// Thumbnails local store
Meteor.thumbsLocalStore = new UploadFS.store.Local({
    collection: Meteor.thumbs,
    name: 'thumbnails',
    path: '/uploads/thumbnails',
    transformWrite: function (from, to, fileId, file) {
        // Resize to 200x200 in JPEG 75%
        from.pipe(ImageMagick.streams.convert({
            width: 200,
            height: 200,
            format: (/^jpg$/i.test(file.extension) ? 'JPEG' : file.extension).toUpperCase(),
            quality: 75
        })).pipe(to);
    }
});

// Multi store
Meteor.multiStore = new UploadFS.store.Multi({
    name: 'images',
    collection: Meteor.images,
    // Images are read from this store
    defaultStore: Meteor.originalLocalStore,
    stores: [
        Meteor.originalLocalStore,
        Meteor.thumbsLocalStore
    ]
});
```

**Comment by jalik** [comment]
@rodrigok hey, did you ever created thumbnails using UploadFS ?
And what do you think about the concept of a Multi Store explained above ?

**Comment by rodrigok** [comment]
Hi @jalik, sorry by the delay.

I didn't create thumbnails yet, but we will need this feature for Rocket.Chat soon.

I liked the Multi Store concept. How is the development? Can I help in something?

In your concept there is some way to prevent to save the file in a store, example: I'm uploading a PDF file and I don't need the thumbnail because I can use one PDF icon.

I don't know if it makes sense.

**Comment by jalik** [comment]
Multi Store was not that easy to implement, instead I added a `copyTo` option that you can use in any store and that allows to copy stream to a list of stores, it's more powerful as you can cascade copies easily.

https://github.com/jalik/jalik-ufs#copying-files-since-v036

**At the moment, this feature is experimental and not published yet because there are some bugs to fix, if you want to test and use it, you have to checkout the sources of this repo and copy them in the `packages` folder of your app.**
