### ISSUE TITLE
How to upload multiple files ?

### ISSUE THREAD

**Issue by firewater** [jalik/jalik-ufs#22]
Hello, what is the correct way to configure UFS to allow upload of multiple files?

Right now I have the `multiple` attribute set on the `input` element:

```javascript 
<template name="upload">
	<p>Select files to upload:</p>
	<input type="file" multiple>
</template>
```

When I select more than one file to upload, only one file is uploaded.

Thanks

**Comment by jalik** [comment]
Hi @firewater, the way to upload one or more files is the same, however you actually found a bug in the `UploadFS.readAsArrayBuffer()` that was not taking multiple files, but it is now fixed in the **v0.3.1**.
Thank you !

FYI, you can download **UFS-Examples** to try the package or use it as a sandbox for your tests, it's available here : https://github.com/jalik/ufs-example
