### ISSUE TITLE
Question: upload.abort()

### ISSUE THREAD

**Issue by firewater** [jalik/jalik-ufs#23]
Question about `upload.abort()`. Let's say several files are uploading and one of them fails to upload. If I call `upload.abort()` in `onError` does that only abort the failed upload or all remaining uploads?

Thank you for this excellent package!

**Comment by jalik** [comment]
Hi @firewater, there is one uploader (worker) per file to upload, so any action on this uploader concerns only one file, in your case it will only abort the file that failed to upload, the others will still be uploading.

I fixed the **abort()** method, it was doing nothing because of a code executed at the wrong place... sorry for that.

Thanks for your help in debugging the package ;-)
