### ISSUE TITLE
Question: download file as file name, not ID

### ISSUE THREAD

**Issue by firewater** [jalik/jalik-ufs#26]
Hi jalik. I have a question about downloading files.

Say I upload a file named `my_file.txt` and the server assigns a Mongo ID of `12345` to this document. When I try downloading that file, it is saved on my computer as `12345.txt` instead of `my_file.txt`.

Is there a way to configure UFS to allow downloads by file name, not ID ?

Thank you

**Comment by jalik** [comment]
Hi @firewater it's currently not supported, I'll try to implement this feature ASAP, it has been asked already, the only problem is to find a way to migrate from the previous (current) behavior to the next one (the one you want) because it depends on the URL. I'll tell you when it's done.

**Comment by jalik** [comment]
@firewater Hey, since the version **0.3.4** the default behavior is to save the file URL using this pattern : `"storeName/fileId/name.extension"`, but don't worry about the old URLs, they still works because the previous pattern is still supported `"storeName/fileId.extension"`.

If you want to update the old URLs with the new pattern, adapt the code below for each store :
```js
Meteor.startup(function () {
    var store = Meteor.photosStore;
    Meteor.photos.find({
        store: store.getName()
    }, {fields: {_id: 1}}).forEach(function (photo) {
        Meteor.photos.update(photo._id, {
            $set: {url: store.getFileURL(photo._id)}
        });
    });
});
```

**Comment by firewater** [comment]
@jalik 

Thank you for this update. The files are now downloading by file name instead of ID, which is very helpful.

However, something has changed. When the files are downloaded, their size is zero bytes. I am not sure why. Here is my onRead code (worked with **previous version**):

```javascript
// Called before reading file to check if we can return it.
onRead: function (fileId, request, response) {
	var doc = biotools_uploads.findOne(fileId);
	if (doc) {
		// User must own file to download it.
		if (doc.userId !== request.userId) {
			throw new Meteor.Error(403, 'this file is private');
		}
	} else {
		throw new Meteor.Error(404, 'file not found');
	}
}
```

...and here is the code in the documentation:

```javascript
onRead: function (fileId, file, request, response) {
    // Allow file access if not protected or if token is correct
    if (file.token === null || request.query.token === file.token) {
        return true;
    } else {
        response.writeHead(403);
        return false;
    }
}
```

Is my code not valid as of **version 0.3.4**? Again, thank you for his great package!

**Comment by jalik** [comment]
Hi @firewater, it's not obvious in the doc, but as the example shows you have to return `true` in the `onRead()` method to allow the access to the file, returning anything else is equivalent to returning `false` to deny the access to the file.

So taking your code you should do the following :

```js
// Called before reading file to check if we can return it.
onRead: function (fileId, file, request, response) {
    // No need to check if file is null because the 404 error is handled automatically by UploadFS.
    // In this method, fileId, file, request and response are never null
    // User must own file to download it.
    if (file.userId === request.userId) {
        return true;
    } else {
        // This returns the 403 HTTP code to the client without throwing an error
        response.writeHead(403);
        // This denies the access to the file
        return false;
    }
}
```

**Comment by firewater** [comment]
@jalik thank you for clarifying. After making the changes to my code, it now seems that `request.userId = undefined`. What is the correct way to do `if (file.userId === request.userId) {...`?  Thanks!

**Comment by jalik** [comment]
@firewater I am sorry, I did not test the code... but I remember it's not possible to get the userId from the HTTP request, not even from `Meteor.userId()` or `Meteor.user()` inside the `onRead()` method because it's not executed in a **Fiber**. That's why in the doc the example is using a token like a password to access the file.

You could explicitly add the **userId** to the file's URL :
```html
{{#with image}}
<img src="{{url}}?userId={{currentUser._id}}">
{{/with}}
```

Then you get the **userId** from the query params :
```js
onRead: function (fileId, file, request, response) {
    if (file.userId === request.query.userId) {
        return true;
    } else {
        response.writeHead(403);
        return false;
    }
}
```

It will work but I would suggest you to go with the token pattern as it's more secure, a userId is easy to get and so anybody having the userId can access the file, the token on the other hand can be published (made available) only to the owner of the file, so it guarantee that only the owner can access the file because he is the only one to know the token. The token could also be shared to a small group of users so it's more flexible. Think about it.

**Comment by firewater** [comment]
Hi @jalik , Thank you for clarifying again. Since the token pattern is more secure, I will choose to use that pattern instead of `userId`.

However, I am unsure how to use this pattern. At the moment, it appears `file.token = undefined` & `request.query.token = undefined`. Therefore, files are not protected yet. Do I need to create a token system? If so, can you please provide code examples?

Thanks for your help

**Comment by jalik** [comment]
@firewater The implement of the token pattern is free, but since it could be useful for the mass, I've included it as an automatic mechanism since the **v0.3.5**.

So from now you have to upgrade the **jalik:ufs** package and any file downloaded in the future will have a token automatically.

If you want to use your own token generation algorithm, you'll have to overwrite the `UploadFS.generateToken()` method (here is the current implementation : https://github.com/jalik/jalik-ufs/blob/master/ufs.js#L64-L70).

To add a token to your existing files, adapt and execute the code below :
```js
Meteor.startup(function () {
    Files.find({
        $or: [
            {token: {$exists: false}},
            {token: null}
        ]
    }).forEach(function (file) {
        Files.update(file._id, {
            $set: {token: UploadFS.generateToken()}
        });
    });
});
```

**Comment by swamykumarv** [comment]
Hi Jalik,

I am using 0.6.8 version, still files uploading to folder with id, how can give file name as per my need?

I wanted to give file name like filename_datestamp.*

is this possible with UFS?

**Comment by jalik** [comment]
@swamykumarv, you've misunderstood this issue, initially it was about downloading stored file from the server to the client using the file name.

In your case, you are talking about "storing" the file on the server with the file name instead of the file ID.
UploadFS does not provide this feature now, but maybe in the future.

**Comment by swamykumarv** [comment]
Hi Jalik,

Thanks much for reply.
