### ISSUE TITLE
Error when upload an empty file

### ISSUE THREAD

**Issue by rodrigok** [jalik/jalik-ufs#29]
![captura de tela 2015-12-21 as 09 55 14](https://cloud.githubusercontent.com/assets/234261/11930264/0247f0d6-a7c9-11e5-9cd4-1842c50ed30d.png)

Maybe you can check the size of the file or add an option to define a minSize in Filters.

**Comment by jalik** [comment]
@rodrigok Could you test the last commit to see if that changes something for you ? I haven't noticed any server crash since any error/expection is handled by a domain. Also uploading a zero byte file works fine for me... What I see in your configuration is that you use a /tmp/ufs folder, that means when your computer restarts the /tmp is cleared so any file in there is deleted, this leads to an error message in the console but not the one you gave.

To test a commit, just update the project and create a symlink that references this package in your project's **packages** folder, Meteor gives priority to local packages if present.

**Comment by jalik** [comment]
@rodrigok Please could you confirm that this bug has been fixed ? Thanks

**Comment by rodrigok** [comment]
Yes, is working, thanks :smile:
