### ISSUE TITLE
Best Way for Server to Upload Large Files?

### ISSUE THREAD

**Issue by graywolf336** [jalik/jalik-ufs#32]
Right now I'm working on an item for Rocket.Chat, importing data over from Slack and one of the issues I've ran into is when a file is large, 157706799 bytes to be exact, Rocket.Chat runs out of memory and crashes. @rodrigok told me to create a new issue since the client handling this is done differently.

Right now I am downloading the file with `HTTP.get message.file.url, npmRequestOptions: {encoding: 'binary'}` and then converting it into a stream and passing that over to ufs.

I get the feeling I need to get the file as a stream and then pass that stream over to ufs, but I'm not sure if that's even right or even possible.

Thanks in advance for the help!

**Comment by jalik** [comment]
Hi @graywolf336, I am not sure if I understand your problem, you have a big file of 157MB that you need to save in a store ?

You're also talking about downloading, so does the crash happens when you want to store (write) the file or when you want to download (read) it ?

It could be nice also if you post here or give me a link to your code, I could debug it.

But one thing is sure, UFS like CFS are using streams to read/write files so at one moment you need to use a stream.

**Comment by graywolf336** [comment]
```coffeescript
result = HTTP.get 'https://slack-files.com/files-pub/T0315A101-F07U76L8P-01eeb004c0/20150721_000204.mp4', npmRequestOptions: {encoding: 'binary'}
rs = RocketChatFile.bufferToStream new Buffer(result.content, 'binary')
fileId = Meteor.fileStore.create details
Meteor.fileStore.write fileStream, fileId, (err, file) ->
  if err
    console.error err
  else
    console.log "#{file.name} saved to the store."
```

Here is the code which I was suggested to use. Currently it works okay for smaller sized files, but larger files it bogs down the server and sometimes runs out of memory (like the file url given).

Basically I'm downloading the file from Slack and then importing them.

What would be your recommendation?

**Comment by graywolf336** [comment]
And it is crashing when I convert from a buffer to a stream. So, guess I'm wondering how to pipe the data from `HTTP.get` directly into the fileStore's write method.

**Comment by jalik** [comment]
Hi @graywolf336, so I tried to upload a file of 300MB+ from the client using the `UploadFS.Uploader` and it worked, then I tried to write the same file on the server using the `UploadFS.store.Local` and it worked well also.. I must admit I had no problem storing a big file so you should not.

Streams are designed to handle small to big files that's why we use them.
I think the problem is that you are using the Meteor's `HTTP` package which returns the content of the file as a string which causes the OutOfMemory exception, I would strongly recommend you use the NodeJS `http` module, I did it and it worked like a charm :

```js

if (Meteor.isServer) {
    var http = Npm.require('http');

    Meteor.startup(function () {
        http.get('https://slack-files.com/files-pub/T0315A101-F07U76L8P-01eeb004c0/20150721_000204.mp4', Meteor.bindEnvironment(function (stream) {
            // Declare file in DB
            var fileId = Meteor.fileStore.create(details);

            if (fileId) {
                Meteor.fileStore.write(stream, fileId, function (err, file) {
                    if (err) {
                        console.error('Error writing file', err.message);
                    } else {
                        console.info('File successfully stored', file);
                    }
                });
            }
        }));
    });
}
```

**Comment by graywolf336** [comment]
I will try it tomorrow and report back, thanks for your help!

**Comment by jalik** [comment]
@graywolf336 I successfully downloaded the video file using the code above with `https` node module.
There is nothing wrong with **UploadFS** (hopefully). Let me know if you made it.

**Comment by graywolf336** [comment]
Awesome, that worked wonders! :+1: thanks for your help on this!!!
