### ISSUE TITLE
Images dont download after migrating

### ISSUE THREAD

**Issue by skemb321** [jalik/jalik-ufs#38]
Hi @jalik,

I recently moved my database to a separate server. When I was doing the tranfser/migrate, I just did mongodump from my old server and mongorestore it to the new one. The bad news is, the images from the old server are not rendered/downloaded. In the network tab of devtools it says 'EMPTY_RESPONSE'. Did i miss something? Please help

**Comment by jalik** [comment]
Hi @skemb321, what you did is to migrate the files informations (name, type, size...) which are stored in mongodb, but for the files data, it depends on which store adapter you used, (ex: local, gridfs...).

So for example, if you used the local store adapter which stores files on the local filesystem, then you also need to copy all files located in the path referenced by the local store, I think it's your case.

**Comment by skemb321** [comment]
We are using gridfs. We are also running a small installation of rocketchat but decided to separate the database from the app server. Where is it stored for gridfs? I have observed that when uploading it will store it temporarily in /tmp/ufs but will delete the file after it's uploaded.

**Comment by jalik** [comment]
@skemb321 as you noticed, downloading files are temporarily stored to the local filesystem, but when complete they are sent to the store adapter (GridFS in your case).

1. Did you compare the size of the database to check if it's correct ? I mean if you saved files to mongodb, then your database would sizes some MB at least.

As I am not the author of the GridFS, I don't really know how it works, but data should be on the same mongo db then the meteor app collections (unless you have a special configuration).
https://github.com/jalik/jalik-ufs-gridfs/blob/master/ufs-gridfs.js

2. You said that you are using rocketchat too, so you have 2 meteor apps running ? because files uploaded by rocketchat would be stored on a different database I guess ?

3. Did the domain name changed ? when files are saved a URL is saved also, so if you changed your domain, the link is broken (it can be fixed however).

You should investigate by getting a document of your files collection and checking if attribute values are coherent with your current install.

**Comment by skemb321** [comment]
I found this article. Didn't try it but might be helpful to anyone http://stackoverflow.com/questions/8927062/how-can-i-backup-a-mongodb-gridfs-database-the-easiest-way

**Comment by jalik** [comment]
@skemb321 it's been a long time, but have you find a solution to your problem ?
