### ISSUE TITLE
What about transfers that exceed 1gb?

### ISSUE THREAD

**Issue by verrochio** [jalik/jalik-ufs#39]
As the documentation states, UploadFS needs ArrayBuffer as a data input.
Uploading a large file using that method freezes the browser as it has to parse all of the binary data into a string before it can send it to the server.
Is there a way of directly sending the binary blob through the server?

**Comment by jalik** [comment]
Hi @verrochio, I tried to upload files of hundred MB on localhost only and it works, however I haven't tested GB files.. but I understand the problem. I currently don't really have the time to work on this issue, but for sure it's on the todo list for improvements.

I haven't look yet if it's possible to do a stream like reading on the browser, but it will mostly depends of the HTML5 File API limits.

**Comment by KaizenCris** [comment]
I also have this problem. I tried to upload a 3GB video and realized ArrayBuffer could not manage the work. Is there a way to send the data using other method?

**Comment by jalik** [comment]
Hi @KaizenCris, currently there's no other solution, UFS uses Meteor's methods to upload file content in small parts to not block the browser.

I will try to use the `file.slice()` method I just found, maybe it will solve this problem.
http://stackoverflow.com/questions/18586839/read-file-stream-using-javascript-in-web-browser

**Comment by jalik** [comment]
@KaizenCris & @verrochio please update your UFS package and try again with large files.

I've released the version `0.6.0` (https://github.com/jalik/jalik-ufs/commit/dba87a0edc847474d56a422bedfacfe88a7c596e) that should solve this problem, I did some tests with a file of `4.3GB` and it worked well, but took about 30 minutes with the settings I've defined.

**Comment by verrochio** [comment]
@KaizenCris, @jalik Karl, although you are doing an awesome job with UFS converting files to strings inside the browser is not always a good solution. This is what I ended up doing, maybe it helps someone.

1. use whatever js upload script on the client side i used dropzone.js
2. serverside use a "serverside router" (Picker) to create an endpoint for your upload
3. serverside use "multer" to handle uploads for nodejs
3. after download completes (uploaded to s3 in my case) store the location and name, size etc in a collection in the database.

here's a pastebin for my serverside route 
http://pastebin.com/QdeENu1Q

If  you also need the client side, i will gladly help.

**Comment by KaizenCris** [comment]
@verrochio, it would be a great help if you had the client code. =)
Thanks!

**Comment by KaizenCris** [comment]
@jalik I just tried 0.6.0 It works perfect! I'll be using the code today so I'll tell you if I find something else =)

**Comment by jalik** [comment]
@verrochio I completely agree with you, when I started UploadFS, I used Meteor methods (websocket) because it was the quickest and easiest way to do the job (that's what I was thinking at the moment).

However I quickly noticed that it was poor in term of performances, that's why I ended up to the same conclusion as you, using standard HTTP POST/PUT transfers. Hopefully I designed the API with enough abstraction and flexibility to change/improve the code without breaking user's apps.

I did some tests yesterday and it's really faster than the current algorithm, but I still need to adapt the security pattern because it's completely different (userId is not available with POST, it is with methods).

I am planning to release that improvement in the next release `0.6.1` as soon as possible.
I've created the #45 issue for this improvement.
Thank you for your feedbacks @verrochio, @KaizenCris
