### ISSUE TITLE
real projects

### ISSUE THREAD

**Issue by fortunto2** [jalik/jalik-ufs#47]
Hi, I love your package.
 I want to try. But as his condition in terms of stability of work on real projects?
can be used? 
With s3 work chunk upload?

**Comment by jalik** [comment]
Hi @fortunto2, thank you, I know that **RocketChat** uses `UploadFS`, I also use it in one of my projects, I don't know for other users, however I think that you can use it in production since the API is relatively stable (I changed some things in the last version, but it was needed to make a huge improvement in performances).

About Amazon S3, I am not the author of the package so I can't say.

**Comment by fortunto2** [comment]
Thank for answer :+1:
