### ISSUE TITLE
Rename File on transformWrite

### ISSUE THREAD

**Issue by johnmore** [jalik/jalik-ufs#49]
Hi Jalik, maybe I'm not seeing it but I can't seem to find a way to rename the file on transformwrite. I usually use grunt to create my several versions of the same image but was trying to get that onto my server on upload and if I could only change the name of the final file like "-HD", "-Big", "-small" I think I can get this resizing thing working.

Could you help me out?

**Comment by jalik** [comment]
Hi @johnmore, I don't really understand, are you trying to rename the file in database or the physical file in the store ? Could you show me your code to help me better understand what you are trying to do ?

**Comment by johnmore** [comment]
If possible I would want to rename both. No code using your package yet, wanted to switch to it though.

I guess it's easy to explain let's say I'll be uploading a file called image.jpg on the server I want to store it and generate three extra files from it with different dimensions called image-hd.jpg, image-big.jpg and image-small.jpg. Basically I would be using your COPY and sending the files through different stores so that I could achieve that result but I need to be able to change the file-name on Write. Possible?

**Comment by jalik** [comment]
@johnmore, you could use the `Store.onFinishUpload()` event like this :
```js
PhotoBigStore.onFinishUpload = function(file) {
    let newName = file.name.replace('.' + file.extension, '') + '-big.' + file.extension;
    Photos.update(file._id, {$set: {name: newName}});
}
PhotoSmallStore.onFinishUpload = function(file) {
    let newName = file.name.replace('.' + file.extension, '') + '-small.' + file.extension;
    Photos.update(file._id, {$set: {name: newName}});
}
```

But you only rename in database, there is currently no way to rename a physical file.
There is an obvious reason for that, the file is stored with a name corresponding to this pattern `{_id}.{extension}`, if you would be able to rename the file you could overwrite an existing file, so you would need to handle the case when a file has the same name but is different, this never happens with ids.

This behavior is the best I found because :
- You don't have to manage existing files with the same name (no collision)
- It's easy to match a physical file with a database file using the file ID contained in the file name
- Several files can have the same name in database, but a unique name in the  store
- It's more reliable as you can rename the file in database without having to rename it in the store so it won't break existing links

At the end, when you display or download a file, the real name is used, not the ID, so it's transparent for users.

Is it really a problem for you ? I think that the way files are stored is not the way that you browse the files yourself like you do on your personal computer, it's structured for servers, so real names doesn't matter, only simplicity, performance and reliability matters.
