### ISSUE TITLE
Unable to get it working on mobile devices (IOS and Android)

### ISSUE THREAD

**Issue by rawacharya** [jalik/jalik-ufs#58]
Having been banging my head around and trying to get it work with image upload, I finally decided to create an issue. I am trying to create a mobile-only app on Meteor that allows my app users to upload images. Came to know about this pretty awesome package and decided to use it. 

I am using the following code snippet to upload an image from the client. 

```
export const upload = (dataUrl, name, provider, resolve, reject) => {  

	const blob = dataURLToBlob(dataUrl);  

	const photo = {
		name: name,
		size: blob.size,
		type: blob.type,
		provider: provider
	};

	const uploader = new UploadFS.Uploader({
	 store: ImagesStore,
	 data: blob,
	 file: photo,
	 onError: reject,
	 onComplete: resolve
	});

	uploader.start();
};
```
I am using the following to run the app:

`meteor run android-device ios --settings settings.json --mobile-server [Port forwarded external IP]`

I have my app installed and running on both platforms.

Everything runs fine, except when trying to upload images it gives me the following error on Android (when using chrome web-inspector) 

```
jalik_ufs.js?hash=b48a63c…:1365 POST http://localhost:3000/ufs/images/Mp49AAzGnXrxwticN?token=cbbbcaf8a8&progress=0.891597736177623 net::ERR_CONNECTION_REFUSED(anonymous function) @ jalik_ufs.js?hash=b48a63c…:1365self.readChunk @ jalik_ufs.js?hash=b48a63c…:1276(anonymous function) @ jalik_ufs.js?hash=b48a63c…:1321self.sendChunk @ jalik_ufs.js?hash=b48a63c…:1367(anonymous function) @ jalik_ufs.js?hash=b48a63c…:1393(anonymous function) @ meteor.js?hash=0b0ea10…:1133_maybeInvokeCallback @ ddp-client.js?hash=bb47c27…:3557receiveResult @ ddp-client.js?hash=bb47c27…:3577_livedata_result @ ddp-client.js?hash=bb47c27…:4742onMessage @ ddp-client.js?hash=bb47c27…:3385(anonymous function) @ ddp-client.js?hash=bb47c27…:2736_.each._.forEach @ underscore.js?hash=27b3d66…:149self.socket.onmessage @ ddp-client.js?hash=bb47c27…:2735REventTarget.dispatchEvent @ ddp-client.js?hash=bb47c27…:175SockJS._dispatchMessage @ ddp-client.js?hash=bb47c27…:1160SockJS._didMessage @ ddp-client.js?hash=bb47c27…:1218that.ws.onmessage @ ddp-client.js?hash=bb47c27…:1365
jalik_ufs.js?hash=b48a63c…:1365 POST http://localhost:3000/ufs/images/Mp49AAzGnXrxwticN?token=cbbbcaf8a8&progress=0.891597736177623 net::ERR_CONNECTION_REFUSED(anonymous function) @ jalik_ufs.js?hash=b48a63c…:1365self.readChunk @ jalik_ufs.js?hash=b48a63c…:1276(anonymous function) @ jalik_ufs.js?hash=b48a63c…:1321self.sendChunk @ jalik_ufs.js?hash=b48a63c…:1367withValue @ meteor.js?hash=0b0ea10…:1105(anonymous function) @ meteor.js?hash=0b0ea10…:492(anonymous function) @ meteor.js?hash=0b0ea10…:1133
```

And when using Safari Web-inspector I get the following:

`XMLHttpRequest cannot load http://localhost:3000/ufs/images/xFnciqqimy7Rq6rhc?token=5bE858db99&progress=0.43186251252042807. Origin http://localhost:12968 is not allowed by Access-Control-Allow-Origin.`

Any help would be much appreciated.

Thanks

**Comment by Narkoleptika** [comment]
Same problem.

I've tried everything I can think of and now I'm out of things to try and places to look.

I've tried adding to mobile-config.js:

`App.accessRules('*');`

Setting browser-policy on the server:

`import { BrowserPolicy } from 'meteor/browser-policy-common';

Meteor.startup(function() {
    BrowserPolicy.content.allowSameOriginForAll();
    BrowserPolicy.content.allowDataUrlForAll();
    BrowserPolicy.content.allowOriginForAll('*');
    BrowserPolicy.content.allowConnectOrigin("*");
});`

and enabling CORS, also on the server:

`import { WebApp } from 'meteor/webapp';

WebApp.connectHandlers.use((req, res, next) => {
    res.setHeader("Access-Control-Allow-Methods", "POST");
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type");
    if (req.method === 'OPTIONS') {
        res.writeHead(200);
        res.end();
        return;
    }
});`

I even tried removing crosswalk because desperation.

No matter what I try the result is the same.

Here have some screenshots:

<img width="825" alt="screen shot 2016-08-12 at 12 31 53 pm" src="https://cloud.githubusercontent.com/assets/7088166/17637968/f7bbb4b8-609b-11e6-941a-45fff6e4f4b6.png">

<img width="633" alt="screen shot 2016-08-12 at 12 32 06 pm" src="https://cloud.githubusercontent.com/assets/7088166/17637971/fcccda22-609b-11e6-913d-f882e53b3a17.png">

<img width="836" alt="screen shot 2016-08-12 at 12 32 22 pm" src="https://cloud.githubusercontent.com/assets/7088166/17637974/025c248e-609c-11e6-8c4b-4f476e52b3ac.png">

The 'provisional headers are shown' warning under request headers leads me to believe that the request is being stopped before it even makes it out of the client. No preflight? I'm not sure where to look next.

Please help

**Comment by rawacharya** [comment]
I think, `Meteor.absoluteUrl()` is the culprit here.

When I try logging `Meteor.absoluteUrl()` within the upload method, it does return my root URL which in my case is my router's external IP:Port. 

```
export const upload = (dataUrl, name, provider, resolve, reject) => {  

    const blob = dataURLToBlob(dataUrl);  
    console.log(Meteor.absoluteUrl('test')); // Returns my external IP:Port/test
    const photo = {
        name: name,
        size: blob.size,
        type: blob.type,
        provider: provider
    };

    const uploader = new UploadFS.Uploader({
     store: ImagesStore,
     data: blob,
     file: photo,
     onError: reject,
     onComplete: resolve
    });

    uploader.start();
};
```
For some reason, the Meteor.absoluteUrl() invoked from within 'ufsCreate' method is returning http://localhost:3000 as the root URL.
 


Thanks
Raman

**Comment by Narkoleptika** [comment]
Thanks to @rawacharya's tip about Meteor.absoluteUrl, I've managed to get it working on android (hopefully iOS).

I changed the ufs-store getUrl so that it calls a server method.
That server method in ufs-methods uses os to get the server ip and return the url as previously expected.
And in the ufs-server, after a store is found, allow the origin to continue with the request.

I've submitted a pull request with these changes. Check it out. Make sure it works somewhere other than my computer. xD 

#59

**Comment by jalik** [comment]
Thank you @Narkoleptika ! I'll give a look at your code and accept the PR once I am sure that it does not introduces bugs with existing apps.

**Comment by jalik** [comment]
@Narkoleptika I am sorry your PR is not working because you hardcoded your network interface (`en0`), which on my computer is for example `eth0`, it could even be `enp3s0f2` or whatever, it's not the same for everyone so this solution is not usable sadly.

But I better understand what is wrong now, `Meteor.absoluteUrl()` is not really the problem, when you run your app you have to set the mobile server :
`meteor run android-device --mobile-server=http://192.168.3.7:3000`

Yo also have to set the ROOT_URL environment variable before running the app :
`export ROOT_URL=http://192.168.3.7:3000 && meteor run android-device`

Now the problem is that Meteor 1.3 introduces a new way to serve local files on mobile devices :
https://guide.meteor.com/mobile.html#accessing-local-files-and-remote-resources
I don't really understand what I should do... I don't find any doc to show how to handle mobile uploading code.

I just can't even send file from the client, I am using the `UploadFS.selectFiles()` :
And the console.log() is not called like if the **onchange** callback is never called.
```js
UploadFS.selectFiles = (callback) => {
        let img = document.createElement('input');
        img.type = 'file';
        img.multiple = true;
        img.onchange = (ev) => {
            let files = ev.target.files;
            
            console.log(files);

            for (let i = 0; i < files.length; i += 1) {
                callback.call(UploadFS, files[i]);
            }
        };
        img.click();
    };
```

**Comment by Narkoleptika** [comment]
@jalik Damn! I was hoping to get a pull request in before you got to this point xD

I realized this was an issue last night when I uploaded to my staging server and blew everything up. I'm about half way through a solution that either returns Meteor.absoluteURL or an ip if Meteor.absoluteUrl returns localhost. I haven't yet tested if setting --mobile-server makes a difference here. I believe it's being set during the build process for staging, but it's definitely not being set for local testing. At least in my case.

As for the issue you're experiencing now, Try uploading the file multiple times, at least 4 times. I've found that in testing the app I had to initiate the download process multiple times before it actually started.

**Comment by Narkoleptika** [comment]
@jalik **Update**
So setting ROOT_URL and --mobile-config on local env definitely fixes the url thing.
I'm reverting the store.getUrl to it's previous state of simply returning Meteor.absoluteURL, removing os as a dependency and removing the ufsGetUrl method entirely.

The `res.setHeader("Access-Control-Allow-Origin", req.headers.origin);` call in the server is still needed for mobile apps to work properly.

And I'll probably throw something in the readme about setting ROOT_URL and --mobile-server for local app development.

Now I'm looking into why you need to upload a photo  4  or more times in order to start the upload process.

Let me know if you find anything. Thanks

**Comment by jalik** [comment]
@rawacharya Could you upgrade UFS to the 0.6.3 version and tell me if it solves your problem ? Thank you. You should also give a look to the [mobile testing doc](https://github.com/jalik/jalik-ufs/blob/v0.6.3/README.md#mobile-testing).

**Comment by rawacharya** [comment]
Thanks @jalik.I will give it a go tomorrow and will let you know the outcome.

**Comment by ardwyn** [comment]
That seems to have fixed all the issues I was having.  IOS works, Android works, PC works.  All using web interface.  Thank you!

**Comment by AnshD12** [comment]
@jalik  I am trying to call http request on the url 
`https://localhost:3000/ufs/FileSystem:Uploads/dbhunjCWzLoZNoTqJ?token=e858497a7b` 
`let data = {
          byteCount : 16384,
          content :  new Buffer(item, 'base64'),
          contentType : "image/jpeg",
          offset : 0
        }`

`let options = {
          "data" : data,
          "headers" : {
            "Cookie" : cookie,
            "Content-Type" : "image/jpeg",
            "User-Agent": "METEOR/1.5.2.2",
            "accept-encoding": "gzip"
          }
          // "headers" : cookie
        };`

`HTTP.call("POST", url ,options ,function(error, result){

          if(error){
            // console.log("options");
            // console.log(options);
            console.log("error", error);
            future.return(error);
          }else{
             console.log("result" , result);
             future.return(result);
          }
        });`

and i am gettig response as 204 and then I am calling ufscomplete but its not working when i open the image its corrupted 

can you help
