### ISSUE TITLE
Several questions about the Store.

### ISSUE THREAD

**Issue by aikonplus** [jalik/jalik-ufs#64]
Hi,

1) When I upload an img, the url of the img is something like:

> http://localhost:3040/ufs/logo/PKnN2rshQPjYTEBsa/logo.png

but shouldn't it be more like?:

> http://localhost:3040**/uploads/logo**PKnN2rshQPjYTEBsa/logo.png

I initialize the store like this:
```
Logo = new Mongo.Collection('logo');
LogoStore = new UploadFS.store.Local({
    collection: Logo,
    name: 'logo',
    path: '/uploads/logo',
    mode: '0744', // directory permissions
    writeMode: '0744', // file permissions
    filter: new UploadFS.Filter({
        minSize: 1,
        maxSize: 1024 * 1000, // 1MB,
        contentTypes: ['image/*'],
        extensions: ['png']
    })
});
```

2) Further more I would like to know where these images are actually stored on my system? I can not find them. They are not in the meteor project folder. I am using Win7.

3) Are the uploaded images automatically deleted if I delete the entry for that image in my Mongo.Collection?

4) If I set up a tunnel to my Localhost, then I can not access the images from other devices (from the outside). It seems like the place where they are stored, is not accessible for other devices, except the mashine where the app is actually running on localhost. Is this only a localhost issue, or do I need to adjust something for the live version?

thank you for your time

**Comment by jalik** [comment]
Hi @aikonplus,

1. The URL path of files is not managed on each store, you define it with `UploadFS.config.storesPath = 'uploads';` which is what you want, it makes your files available with this URL pattern : `http://${host}/${storesPath}/${storeName}/${file._id}/${file.name}`

2. The `path` option of the Local store is the answer, it is the path where files are stored (at least you need to have the path to exists or the permissions to create it by the app), it's not what you thought in the previous question, for example this option does not exists for the  GridFS store as it stores files in database and not in a local `path`.

3. Yes, files are deleted when you delete them from collection. 

4.I don't understand your "tunnel" word, are you talking about a VPN ? whatever when you upload a file, it saves the URL using the current server host address (see the Meteor's `ROOT_URL` env var), so if it is `http://localhost/`, images on the app will display this address and it's not good since it will target client's own machine (localhost). So it's mainly a matter of dev config. If you want to access your dev app from other machines, you need to set the `ROOT_URL` to your server's IP/hostname.

You're welcome.

**Comment by aikonplus** [comment]
H @jalik,

Thank you very much for your support.

2, But where do I need to create that path, or where is it created if the permission is granted?
I can not find it in the Project Folder of my Meteor app. But the images are actually uploaded to somewhere...

4. by "tunnel" I meant the "https://ngrok.com/" - tunnel to my localhost. However you are, of course, right. The url of the img is `http://localhost:3040/ufs/logo/PKnN2rshQPjYTEBsa/logo.png`, but the url of the tunnel is something like` htttp://aD2jw3.ngrok.com/`... of course that does not work. Setting the ROOT_URL solved the problem. But I guess the ROOT_URL is set to the right address when I will deploy the app? So I will not have to modify that one everytime I deploy my app?

**Comment by jalik** [comment]
The Local store is a store that saves files on a path on your computer so the `path` points to a folder on the server. If you start meteor with a user named `meteor` and specify the path to be `/uploads/meteor` you need to create the folder and apply the permissions to the user named `meteor` with `chown` and `chmod`. The path must be absolute and not relative.

**Comment by pedrofg** [comment]
Hi, i have the same behavior of the question asked here. I am not understanding very well how it is supposed to work at the end.

My files are uploaded to my folder /uploads which I set when creating the store.
But the image url in the database and on the screen is the UploadFS.config.storesPath.

If i manually delete an image in my /uploads folder, everything still works.
Is is supposed to work like this? The lib creating more than 1 file of the same image in different paths?

Should i set the storesPath as the same absolute path of the Stores (/upload) ?

If i delete from the collection using the mongodb shell, should the image be deleted automatically? Or it will work if i delete through the code?

**Comment by jalik** [comment]
The "public" URL accessible from users is not the same than where the file is stored, it's not working like a classic HTTP server with static files... here you access files through a URL that is translated into a path (with LocalStore), if you would have used an Amazon cloud storage it would have return the file stored on the cloud, this is why the **FILE URL IS NOT THE REAL PATH**.

You have 3 things to setup for the LocalStore :
- the temporary path on the filesystem where UFS will upload the temporary file before saving it to the store (`UploadFS.config.tmpDir`)
- the stores path to access stored files via URL that should not be changed once files are uploaded or URL will be broken (`UploadFS.config.storesPath`)
- and for the LocalStore, the local path on the filesystem where files will be stored (the `path` attribute of the LocalStore options)

For your questions :

> If i manually delete an image in my /uploads folder, everything still works.

You should not do that, how the database could keep sync if you delete the file manually ?? just delete the file in the collection and the real physical file stored on the filesystem or in the cloud (depending of your store) will be deleted also.

> The lib creating more than 1 file of the same image in different paths?

Only if you create thumbnails of the file by using multiple stores and the `copy` attribute of a store, otherwise only one instance of the file is saved, if not you have misconfigured your app or there is something wrong in your code.

> Should i set the storesPath as the same absolute path of the Stores (/upload) ?

You should not change `storesPath` value until you want to change the path, it will not affect the upload, only the access the view/download files.

> If i delete from the collection using the mongodb shell, should the image be deleted automatically?

How could this be possible since the mongo shell is only the database and not the application ? the hooks to delete files automatically are in the application, stick with the app which does everything automatically or manage the sync yourself manually if you really need to do things in database directly (the code is opensource, fetch it and have a look of how it works if you need to do advanced things).

It's true that the documentation does not give any example of removing a file, sorry for that :
```js
import {Mongo} from 'meteor/mongo';
import {LocalStore} from 'meteor/jalik:ufs-local';

// Declare store collection
const Photos = new Mongo.Collection('photos');

// Declare store
const PhotoStore = new LocalStore({
    collection: Photos,
    name: 'photos',
    path: '/uploads/photos',
    mode: '0744', // directory permissions
    writeMode: '0744' // file permissions
});

// Download the file
let url = 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png';
let attr = { name: 'Google Logo', description: 'Logo from www.google.com' };

PhotoStore.importFromURL(url, attr, function (err, file) {
    if (err) {
        console.error(err.message);
    } else {
        console.log('Photo saved :', file);
        // Removing the file from the collection will automatically remove the file from the store
        Photos.remove({_id: file._id});
    }
});
```

In a hope that it will help you in any way.
