### ISSUE TITLE
[Error: ENOENT: no such file or directory, open '/tmp/ufs/5S3mbsAhkfeL5bEdu']

### ISSUE THREAD

**Issue by oedemis** [jalik/jalik-ufs#68]
If i upload a file it returns with a exception:

W20160823-18:19:48.429(2)? (STDERR) { [Error: ENOENT: no such file or directory, open '/tmp/ufs/5S3mbsAhkfeL5bEdu']
W20160823-18:19:48.430(2)? (STDERR)   errno: -2,
W20160823-18:19:48.430(2)? (STDERR)   code: 'ENOENT',
W20160823-18:19:48.430(2)? (STDERR)   syscall: 'open',
W20160823-18:19:48.431(2)? (STDERR)   path: '/tmp/ufs/5S3mbsAhkfeL5bEdu' }

**Comment by jalik** [comment]
Does the `/tmp/ufs` path exists on your filesystem ?
- If not, change to `UploadFS.tmpDir` to an existing path or create it `sudo mkdir /tmp/ufs`

Does the user that runs your Meteor app has the permission to write to this path ?
- If not, apply the permissions to this user : `sudo chown youruser:youruser /tmp/ufs` and `sudo chmod 700 /tmp/ufs`

**Comment by oedemis** [comment]
I'm already root user, but i have yet another strange behaviour while i'm uploading:
in web-console   : http://localhost:3000/ufs/files/eZf4KXS3J8L3KPXWW?token=994a5b3AF9&progress=0.006596620520385748 net::ERR_CONNECTION_REFUSED
.....

**Comment by jalik** [comment]
Are you using `meteor run android` or something like this ?
If so read the doc : https://github.com/jalik/jalik-ufs#mobile-testing

**Comment by pedrofg** [comment]
Same error here, i don't understand why you close the issue which was not resolved

**Comment by pedrofg** [comment]
i am using windows, and the local package, if i do not set any path, it creates the folder in C:/ which works well, if i set the path to be the root of the project i got this error above.

**Comment by jalik** [comment]
Be sure that the Meteor app has the permissions to write to the destination path, not only the directory but all of its parents.

Example, if your app writes to `/data/user/files/` and is run by the user `user`, you should `chown -R` and `chmod -R` to :
- 755 /data (owned by root:root)
- 775 /data/user (owned by user:root)
- 775 /data/user/files (owned by user:root)

Note that this plugin haven't been tested (by myself) on windows platform, so it could be platform related, but since you said it works fine with `C:` path, it should work with any path unless you set the right permissions.
