### ISSUE TITLE
Read file from store

### ISSUE THREAD

**Issue by talha-asad** [jalik/jalik-ufs#70]
From Readme:

```js
// Get the file from database
var file = Photos.findOne(fileId);

// Get the file stream from the store
var readStream = PhotosStore.getReadStream(fileId, file);

readStream.on('error', Meteor.bindEnvironment(function (error) {
    console.error(err);
}));
readStream.on('data', Meteor.bindEnvironment(function (data) {
    // handle the data
}));
```

Why do you have to give `fileId` and `file` both to `getReadStream`, shouldn't it be just `fileId`?

**Comment by jalik** [comment]
Hi @talha-asad, it's because first there was only the `fileId` argument, but since you want the file object instead of just the file ID in the transform methods, I've added the `file` argument and for retro-compatibility I did not remove the `fileId` argument.

Having the file object as an argument avoid users to query the file in database them self, thing that will happen necessarily because need to know at least the file extension/type (MIME) to resize or do transformations.

I agree that it looks useless currently and I will fix that later, the problem is that plugins (GridFS, S3...) that uses those methods will have to quickly follow the change otherwise they will be broken.
