### ISSUE TITLE
Permissions: Are they client-side or server-side?

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#73]
Hi,

This is a question.

According to the [doc](https://github.com/jalik/jalik-ufs#permissions), since v0.6.1 permissions should be set as follows:
```javascript
PhotosStore.setPermissions(new UploadFS.StorePermissions({
    insert: function (userId, doc) {
        return [RESULT OF SOME CHECKS];
    },
    update: function (userId, doc) {
        return [RESULT OF SOME CHECKS];
    },
    remove: function (userId, doc) {
        return [RESULT OF SOME CHECKS];
    }
});
```
On the other hand, the [Meteor Guide](https://guide.meteor.com/security.html#allow-deny) recommends to use  for the app security something like the code below (A):
```javascript
Audios.deny({
  insert: function() { return true; },
  update: function() { return true; },
  remove: function() { return true; },
});
```
There is one more side: The authors of CollectionFS directly emphasize in their documentation that all operations in CFS should be made only from the client. In other words, you can NOT deny `insert` / `update` / `remove` for CFS. So, for any one who has some experience in working with CFS, the question "only client-side?" or "only server-side?" or "both?" arises itself and needs some explanation in the case of UFS, too. 

Moreover, in the UFS doc we read:
> [Version 0.6.1](https://github.com/jalik/jalik-ufs#version-061)
> Uses POST HTTP method instead of Meteor methods to upload files

--- what may imply that similar to CFS we can NOT deny `insert` / `update`  in any form for UFS too, and the only thing that we could do is
```javscript
Audios.deny({
  remove: function() { return true; },
});
```
**The question:**
What are your recommendations? Is it safe to use code like (A) above?

**Comment by jalik** [comment]
Hi @seabrus, your question is legitimate, I need to detail this in the doc.
In fact when you define permissions with the `UploadFS.StorePermissions`, they are checked using https://github.com/matb33/meteor-collection-hooks, so event if the client is allowed to insert/update/remove, your permissions are checked before the action on the server.

You could deny all actions on the client, that UploadFS could still upload the file because it uses `Meteor.methods`  to create and HTTP POST method to send file chunks.

It all depends on you :
- If you only do actions on the client, so allow for client/server (put the real logic on server side)
```js
Audios.allow({
  insert: function() { return false; },
  update: function() { return true; },
  remove: function() { return true; }
});
AudioStore.setPermissions(new UploadFS.StorePermissions({
    insert: function (userId, doc) {
        return userId !== null;
    },
    update: function (userId, doc) {
        return userId !== null && doc.userId === userId;
    },
    remove: function (userId, doc) {
        return userId !== null && doc.userId === userId;
    }
});
```
- If you only do actions on server, deny client and allow server
```js
Audios.allow({
  insert: function() { return false; },
  update: function() { return false; },
  remove: function() { return false; }
});
AudioStore.setPermissions(new UploadFS.StorePermissions({
    insert: function (userId, doc) {
        return userId !== null;
    },
    update: function (userId, doc) {
        return userId !== null && doc.userId === userId;
    },
    remove: function (userId, doc) {
        return userId !== null && doc.userId === userId;
    }
});
```

**What you want to deny every time is the insert on client because it's not used by UploadFS.**

Finally, you said :
> what may imply that similar to CFS we can NOT deny insert / update in any form for UFS too

That's totally wrong since when you define the `insert` in the UploadFS.StorePermissions, you can deny/allow file upload/creation.

**Comment by seabrus** [comment]
@jalik, 

Great explanation, thanks a lot :+1:! Have a nice day :)
