### ISSUE TITLE
How to user userId for onRead permissions?

### ISSUE THREAD

**Issue by colinzhao** [jalik/jalik-ufs#81]
I am quite new to Meteor, so please help if I am asking beginner's questions.

I tried to use `this.userId` for onRead permissions, but it seems this.userId returns `undefined` value.

Is it possible to pass userId to onRead function?

**Comment by jalik** [comment]
@colinzhao `this.userId` is not available everywhere, only inside `Meteor.methods()` and `Meteor.publish()`. Since UploadFS uploads file chunks using HTTP POST and not Meteor's methods, `this.userId` is not available so cannot be passed to `onRead()`.
If you want to secure access to a file, use the URL token pattern, it's in the doc: https://github.com/jalik/jalik-ufs#secure-file-access
