### ISSUE TITLE
Message in console: "ufs: cannot remove file "null" (Token is not valid [invalid-token])"

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs#83]
Hi @jalik,

Please help to clarify a trouble.

I've updated `UFS` and `ufs-gridfs` to `jalik:ufs@0.6.8` and `jalik:ufs-gridfs@0.1.2` today. Before that I reset the app by `meteor reset`. When then I uploaded new file(s), they were added but in the console I saw the following message for each file:

`ufs: cannot remove file "null" (Token is not valid [invalid-token]) --- ufs-uploader.js:157`

The `onError` handler
```javascript
onError: function (err) {
  console.error(err);
},
```
 in the uploader ` let uploader = new UploadFS.Uploader...` also printed in Chrome's console:

`errorClass {error: "invalid-token", reason: "Token is not valid", details: undefined, message: "Token is not valid [invalid-token]", errorType: "Meteor.Error"}`

or in Firefox:

`Object { stack: "Meteor.makeErrorType/errorClass@htt…", error: "invalid-token", reason: "Token is not valid", details: undefined, message: "Token is not valid [invalid-token]", errorType: "Meteor.Error" }`

What is wrong? Can't understand.

Best regards,
seabrus

**Comment by agwm2013** [comment]
I was experiencing the same issue, this is how it started. Using node-inspector, I was able to walk through and determined it was related to #82 

I had audit-argument-checks installed. I removed it from my project, and everything is back to normal. Doesn't look like it will be fixed.  Maybe cloning, making changes, and perhaps submitting a PR.

**Comment by seabrus** [comment]
Hi @agwm2013,

Thanks a lot for the information! Yes, I have audit-argument-checks installed too. I'll try to remove it.

**Comment by jalik** [comment]
There is no problem for this issue, I've installed the `audit-argument-checks` package and tested it.
1. The error is thrown by the package in the `ufsComplete` method after the file has been uploaded successfully
2. This causes the uploader (client side) to abort the download because of the error (which in fact is useless since it's not an error thrown by UploadFS)
3. When aborting the download, it tries to remove the file because aborting means an incomplete file so we don't want to keep incomplete files in stores, but since the upload token was removed when the file was fully uploaded the token does not exist anymore, so the error you see is because of that cleaning process that should not be called because the file IS downloaded successfully.

I will add these `check()` but I feel like forced to do it, in fact it won't add more security, just a double check, but if that can removes warnings and errors, let' do it.

**Comment by seabrus** [comment]
Hi @jalik,

_I will add these check() but I feel like forced to do it, in fact it won't add more security, just a double check, but if that can removes warnings and errors, let' do it_ - agree with you. 

Frankly, often I do the same in my code: use (sometimes quite formally) `check()` only for the compliance with the `audit-argument-checks` package, and then add more detailed and understandable checks of the parameters, for example, using `Match(...)` or other tests. Yes, such an approach leads to a double check, but `audit-argument-checks` is quite useful, as well as it's recommended by MDG. Unfortunately, `audit-argument-checks` is restricted to the `check()` tests only, it is not convenient. Maybe MDG modify it in the future and make it more flexible.

However, thanks for your efforts to make UFS the best package for meteor file uploading. 
Have a nice day!
