### ISSUE TITLE
Do not remove file tokens when file is uploaded

### ISSUE THREAD

**Issue by DoubleChok** [jalik/jalik-ufs#87]
Uploader file tokens needed until uploader deleted (or set to null).

**Comment by jalik** [comment]
I don"t understand how you ended up having the file token removed, could you explain or show me the code you're using to upload ?

FYI, there are 2 kinds of token :
- **Temporary Upload Tokens**, they are stored in their own collection and managed by UploadFS, they are used to transfer chunks of data, if the upload is aborted or completed, these tokens are deleted to avoid any modification of the file later
- **Permanent File Tokens** stored in the file collection as the `token` attribute, they are used as a simple security pattern that you can use or not

**Comment by DoubleChok** [comment]
I handling temporary uploads by keeping uploaders. I use uploader.abort(); to remove temporary uploaded files from database. When a upload became permanent I delete uploader by setting uploader = null.
At version 0.6.8 you remove the file token after file uploaded and I get error "invalid token. file token is null".

**Comment by jalik** [comment]
I am sorry, I really don't understand, can you show me your code ?
Maybe you are doing things in an incorrectly.
File URL is not set until the upload is complete because the URL would point to nothing since the file is actually moved to the store when it has been fully uploaded, so at this time the file can be reached via the URL.

**Comment by DoubleChok** [comment]
Never mind. I will stay at version 0.6.7.
